substitutions:
  _REGION: "us-central1"
  _REPO: "api-totales"
  _SERVICE: "ms-mv-consulta-vehiculo-pt"
  _APP_ENV: "prod"

steps:

  # 1. Build container image con build-arg APP_ENV
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg", "APP_ENV=${_APP_ENV}",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA",
        "."
      ]

  # 2. Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      ]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--image", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",

        # ENV VARS
        "--set-env-vars", "IMAGES_MODE=gs",
        "--set-env-vars", "PROJECT_ID=$PROJECT_ID",
        "--set-env-vars", "LOCATION=${_REGION}",
        "--set-env-vars", "PROMPTS_FILE=prompts.yaml",
        "--set-env-vars", "APP_ENV=${_APP_ENV}"
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA"
